version: '3.1'
services :
  cron_server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      DB_USER: user
      DB_PASSWORD: pass
      DB: apidb
